kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080
        hostPort: 8000
        protocol: TCP
      - containerPort: 30443
        hostPort: 8443
        protocol: TCP
      - containerPort: 30081
        hostPort: 8001
        protocol: TCP
      - containerPort: 30444
        hostPort: 8444
        protocol: TCP
      - containerPort: 30082
        hostPort: 8081
        protocol: TCP
  - role: worker
