{{- if .Values.postgresPassword }}
{{- $secretName := .Values.global.databaseSecret.name }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
{{- if not $existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dex-server.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  {{ .Values.global.databaseSecret.key }}: {{ .Values.postgresPassword | b64enc }}
{{- end }}
{{- end }}
